In [4]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle
import pandas as pd
import numpy as np

WARNING:tensorflow:From c:\Users\shrey\anaconda3\envs\tfenv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [5]:
## load trained model and pickle files

model=load_model('model.h5')

with open('label_encoder_gender','rb') as file:
    label_encoder_gender=pickle.load(file)

with open('oneHotEncoder_geo','rb') as file:
    oneHotEncoder_geo=pickle.load(file)

with open('scaler','rb') as file:
    scaler=pickle.load(file)

WARNING:tensorflow:From c:\Users\shrey\anaconda3\envs\tfenv\Lib\site-packages\keras\src\backend.py:1398: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

In [6]:
## example input data
input_data={
    'CreditScore':600,
    'Geography': 'France',
    'Gender': 'Male',
    'Age':40,
    'Tenure':3,
    'Balance':60000,
    'NumOfProducts':2,
    'HasCrCard':1,
    'IsActiveMember':1,
    'EstimatedSalary':50000
}

In [19]:
## one hot encoding 'geography'
geo_encoded=oneHotEncoder_geo.transform([[input_data['Geography']]]).toarray()
geo_encoded_df=pd.DataFrame(geo_encoded,columns=oneHotEncoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

c:\Users\shrey\anaconda3\envs\tfenv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [20]:
input_df=pd.DataFrame([input_data])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,Male,40,3,60000,2,1,1,50000

In [21]:
from sklearn.preprocessing import StandardScaler,LabelEncoder
label_encoder_gender=LabelEncoder()
input_df['Gender']=label_encoder_gender.fit_transform([input_df['Gender']])
input_df

c:\Users\shrey\anaconda3\envs\tfenv\Lib\site-packages\sklearn\preprocessing\_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,0,40,3,60000,2,1,1,50000

In [22]:
input_df=pd.concat([input_df.drop('Geography',axis=1),geo_encoded_df],axis=1)
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,0,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [23]:
## Scaling input data
input_scaled=scaler.transform(input_df)
input_scaled

array([[-0.47252305, -1.09400025,  0.0906231 , -0.70903082, -0.27592043,
         0.79187296,  0.63599873,  0.97160303, -0.84394851,  0.98728088,
        -0.58166121, -0.56318378]])

In [24]:
prediction=model.predict(input_scaled)
prediction

1/1 [==============================] - 0s 62ms/step

array([[0.06112211]], dtype=float32)